/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Facturas.AnularFactura;

import javax.swing.JOptionPane;

/**
 *
 * @author venot
 */
public class AnularFacturaSeleccionar extends javax.swing.JInternalFrame {
    private ClienteFactura clienteFactura;
    private BuscarPorEmpleado empleadoFactura;
    private javax.swing.JDesktopPane desktopPane;
    private FechaFactura fechaFactura;
    private NumeroFactura numeroFactura;
    
    
    /**
     * Creates new form AnularFacturaSeleccionar
     */
    public AnularFacturaSeleccionar(javax.swing.JDesktopPane p) {
        initComponents();
        buttonGroup.add(jradiobntCliente);
        buttonGroup.add(jradiobntEmpleado);
        buttonGroup.add(jradiobntFecha);
        buttonGroup.add(jradiobntNumeroFactura);
        desktopPane = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jradiobntNumeroFactura = new javax.swing.JRadioButton();
        jbntBuscar = new javax.swing.JButton();
        jradiobntFecha = new javax.swing.JRadioButton();
        jradiobntEmpleado = new javax.swing.JRadioButton();
        jradiobntCliente = new javax.swing.JRadioButton();
        jbntSalir = new javax.swing.JButton();

        jLabel1.setText("Anular Factura por :");

        jradiobntNumeroFactura.setText("Numero de Factura");

        jbntBuscar.setText("Buscar");
        jbntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntBuscarActionPerformed(evt);
            }
        });

        jradiobntFecha.setText("Fecha");

        jradiobntEmpleado.setText("Empleado");

        jradiobntCliente.setText("Cliente");

        jbntSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(0, 555, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jradiobntNumeroFactura)
                .addGap(18, 18, 18)
                .addComponent(jradiobntEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jradiobntCliente)
                .addGap(27, 27, 27)
                .addComponent(jradiobntFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbntBuscar)
                .addGap(25, 25, 25)
                .addComponent(jbntSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradiobntNumeroFactura)
                    .addComponent(jradiobntEmpleado)
                    .addComponent(jradiobntCliente)
                    .addComponent(jradiobntFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbntBuscar)
                    .addComponent(jbntSalir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntBuscarActionPerformed
        if(jradiobntCliente.isSelected()||jradiobntEmpleado.isSelected()||jradiobntFecha.isSelected()||jradiobntNumeroFactura.isSelected()){
            if (jradiobntCliente.isSelected()) {
                
                desplegarCliente();
                
            }else if(jradiobntEmpleado.isSelected()){
                
                desplegarEmplado();
                
            }else if(jradiobntFecha.isSelected()){
                desplegarFecha();
                
                
            }else if(jradiobntNumeroFactura.isSelected()){
                
                
                
            }
        }else{
            JOptionPane.showInternalMessageDialog(rootPane, "Escoja una opcion.");
        }
                
    }//GEN-LAST:event_jbntBuscarActionPerformed
    
    private void desplegarCliente(){
        if(clienteFactura == null){
            clienteFactura = new ClienteFactura();
            desktopPane.add(clienteFactura);
        }
        
        clienteFactura.setVisible(true);
    }
    private void desplegarEmplado(){
        if(empleadoFactura == null){
            empleadoFactura = new BuscarPorEmpleado();
            desktopPane.add(empleadoFactura);
        }
        empleadoFactura.setVisible(true);
    }
    private void desplegarFecha(){
        if(fechaFactura == null){
            fechaFactura = new FechaFactura();
            desktopPane.add(fechaFactura);
        }
        fechaFactura.setVisible(true);
    }
    private void desplegarNumeroFactura(){
        if(numeroFactura == null){
            numeroFactura = new NumeroFactura();
            desktopPane.add(numeroFactura);
        }
        numeroFactura.setVisible(true);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbntBuscar;
    private javax.swing.JButton jbntSalir;
    private javax.swing.JRadioButton jradiobntCliente;
    private javax.swing.JRadioButton jradiobntEmpleado;
    private javax.swing.JRadioButton jradiobntFecha;
    private javax.swing.JRadioButton jradiobntNumeroFactura;
    // End of variables declaration//GEN-END:variables
}
