/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Facturas.AnularFactura;

/**
 *
 * @author venot
 */
public class AnularFacturaSeleccionar extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnularFacturaSeleccionar
     */
    public AnularFacturaSeleccionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jradiobntNumeroFactura = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jradiobntFecha = new javax.swing.JRadioButton();
        jradiobntEmpleado = new javax.swing.JRadioButton();
        jradiobntCliente = new javax.swing.JRadioButton();

        jLabel1.setText("Anular Factura por :");

        jradiobntNumeroFactura.setText("Numero de Factura");

        jButton1.setText("Buscar");

        jradiobntFecha.setText("Fecha");

        jradiobntEmpleado.setText("Empleado");

        jradiobntCliente.setText("Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jradiobntNumeroFactura)
                .addGap(18, 18, 18)
                .addComponent(jradiobntEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jradiobntCliente)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jradiobntFecha))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradiobntNumeroFactura)
                    .addComponent(jradiobntEmpleado)
                    .addComponent(jradiobntCliente)
                    .addComponent(jradiobntFecha))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jradiobntCliente;
    private javax.swing.JRadioButton jradiobntEmpleado;
    private javax.swing.JRadioButton jradiobntFecha;
    private javax.swing.JRadioButton jradiobntNumeroFactura;
    // End of variables declaration//GEN-END:variables
}
